create user TMPSMSI_PUB identified by TMPSMSI_PUB                                     
default tablespace canoe_data                                                   
quota unlimited on canoe_data                                                   
quota unlimited on canoe_index                                                  
quota unlimited on canoe_data_compress                                          
quota unlimited on canoe_data_compress2
/                                                                               
                                                                                
grant ADMINISTER ANY SQL TUNING SET to TMPSMSI_PUB;                                
grant ADMINISTER DATABASE TRIGGER to TMPSMSI_PUB;                                  
grant ADMINISTER RESOURCE MANAGER to TMPSMSI_PUB;                                  
grant ADMINISTER SQL MANAGEMENT OBJECT to TMPSMSI_PUB;                             
grant ADMINISTER SQL TUNING SET to TMPSMSI_PUB;                                    
grant ADVISOR to TMPSMSI_PUB;                                                      
grant ALTER ANY ASSEMBLY to TMPSMSI_PUB;                                           
grant ALTER ANY CLUSTER to TMPSMSI_PUB;                                            
grant ALTER ANY CUBE DIMENSION to TMPSMSI_PUB;                                     
grant ALTER ANY CUBE to TMPSMSI_PUB;                                               
grant ALTER ANY DIMENSION to TMPSMSI_PUB;                                          
grant ALTER ANY EDITION to TMPSMSI_PUB;                                            
grant ALTER ANY EVALUATION CONTEXT to TMPSMSI_PUB;                                 
grant ALTER ANY INDEX to TMPSMSI_PUB;                                              
grant ALTER ANY INDEXTYPE to TMPSMSI_PUB;                                          
grant ALTER ANY LIBRARY to TMPSMSI_PUB;                                            
grant ALTER ANY MATERIALIZED VIEW to TMPSMSI_PUB;                                  
grant ALTER ANY MINING MODEL to TMPSMSI_PUB;                                       
grant ALTER ANY OPERATOR to TMPSMSI_PUB;                                           
grant ALTER ANY OUTLINE to TMPSMSI_PUB;                                            
grant ALTER ANY PROCEDURE to TMPSMSI_PUB;                                          
grant ALTER ANY ROLE to TMPSMSI_PUB;                                               
grant ALTER ANY RULE SET to TMPSMSI_PUB;                                           
grant ALTER ANY RULE to TMPSMSI_PUB;                                               
grant ALTER ANY SEQUENCE to TMPSMSI_PUB;                                           
grant ALTER ANY SQL PROFILE to TMPSMSI_PUB;                                        
grant ALTER ANY TABLE to TMPSMSI_PUB;                                              
grant ALTER ANY TRIGGER to TMPSMSI_PUB;                                            
grant ALTER ANY TYPE to TMPSMSI_PUB;                                               
grant ALTER DATABASE LINK to TMPSMSI_PUB;                                          
grant ALTER DATABASE to TMPSMSI_PUB;                                               
grant ALTER PROFILE to TMPSMSI_PUB;                                                
grant ALTER PUBLIC DATABASE LINK to TMPSMSI_PUB;                                   
grant ALTER RESOURCE COST to TMPSMSI_PUB;                                          
grant ALTER ROLLBACK SEGMENT to TMPSMSI_PUB;                                       
grant ALTER SESSION to TMPSMSI_PUB;                                                
grant ALTER SYSTEM to TMPSMSI_PUB;                                                 
grant ALTER TABLESPACE to TMPSMSI_PUB;                                             
grant ALTER USER to TMPSMSI_PUB;                                                   
grant ANALYZE ANY DICTIONARY to TMPSMSI_PUB;                                       
grant ANALYZE ANY to TMPSMSI_PUB;                                                  
grant AUDIT ANY to TMPSMSI_PUB;                                                    
grant AUDIT SYSTEM to TMPSMSI_PUB;                                                 
grant BACKUP ANY TABLE to TMPSMSI_PUB;                                             
grant BECOME USER to TMPSMSI_PUB;                                                  
grant CHANGE NOTIFICATION to TMPSMSI_PUB;                                          
grant COMMENT ANY MINING MODEL to TMPSMSI_PUB;                                     
grant COMMENT ANY TABLE to TMPSMSI_PUB;                                            
grant CREATE ANY ASSEMBLY to TMPSMSI_PUB;                                          
grant CREATE ANY CLUSTER to TMPSMSI_PUB;                                           
grant CREATE ANY CONTEXT to TMPSMSI_PUB;                                           
grant CREATE ANY CUBE BUILD PROCESS to TMPSMSI_PUB;                                
grant CREATE ANY CUBE DIMENSION to TMPSMSI_PUB;                                    
grant CREATE ANY CUBE to TMPSMSI_PUB;                                              
grant CREATE ANY DIMENSION to TMPSMSI_PUB;                                         
grant CREATE ANY DIRECTORY to TMPSMSI_PUB;                                         
grant CREATE ANY EDITION to TMPSMSI_PUB;                                           
grant CREATE ANY EVALUATION CONTEXT to TMPSMSI_PUB;                                
grant CREATE ANY INDEX to TMPSMSI_PUB;                                             
grant CREATE ANY INDEXTYPE to TMPSMSI_PUB;                                         
grant CREATE ANY JOB to TMPSMSI_PUB;                                               
grant CREATE ANY LIBRARY to TMPSMSI_PUB;                                           
grant CREATE ANY MATERIALIZED VIEW to TMPSMSI_PUB;                                 
grant CREATE ANY MEASURE FOLDER to TMPSMSI_PUB;                                    
grant CREATE ANY MINING MODEL to TMPSMSI_PUB;                                      
grant CREATE ANY OPERATOR to TMPSMSI_PUB;                                          
grant CREATE ANY OUTLINE to TMPSMSI_PUB;                                           
grant CREATE ANY PROCEDURE to TMPSMSI_PUB;                                         
grant CREATE ANY RULE SET to TMPSMSI_PUB;                                          
grant CREATE ANY RULE to TMPSMSI_PUB;                                              
grant CREATE ANY SEQUENCE to TMPSMSI_PUB;                                          
grant CREATE ANY SQL PROFILE to TMPSMSI_PUB;                                       
grant CREATE ANY SYNONYM to TMPSMSI_PUB;                                           
grant CREATE ANY TABLE to TMPSMSI_PUB;                                             
grant CREATE ANY TRIGGER to TMPSMSI_PUB;                                           
grant CREATE ANY TYPE to TMPSMSI_PUB;                                              
grant CREATE ANY VIEW to TMPSMSI_PUB;                                              
grant CREATE ASSEMBLY to TMPSMSI_PUB;                                              
grant CREATE CLUSTER to TMPSMSI_PUB;                                               
grant CREATE CUBE BUILD PROCESS to TMPSMSI_PUB;                                    
grant CREATE CUBE DIMENSION to TMPSMSI_PUB;                                        
grant CREATE CUBE to TMPSMSI_PUB;                                                  
grant CREATE DATABASE LINK to TMPSMSI_PUB;                                         
grant CREATE DIMENSION to TMPSMSI_PUB;                                             
grant CREATE EVALUATION CONTEXT to TMPSMSI_PUB;                                    
grant CREATE EXTERNAL JOB to TMPSMSI_PUB;                                          
grant CREATE INDEXTYPE to TMPSMSI_PUB;                                             
grant CREATE JOB to TMPSMSI_PUB;                                                   
grant CREATE LIBRARY to TMPSMSI_PUB;                                               
grant CREATE MATERIALIZED VIEW to TMPSMSI_PUB;                                     
grant CREATE MEASURE FOLDER to TMPSMSI_PUB;                                        
grant CREATE MINING MODEL to TMPSMSI_PUB;                                          
grant CREATE OPERATOR to TMPSMSI_PUB;                                              
grant CREATE PROCEDURE to TMPSMSI_PUB;                                             
grant CREATE PROFILE to TMPSMSI_PUB;                                               
grant CREATE PUBLIC DATABASE LINK to TMPSMSI_PUB;                                  
grant CREATE PUBLIC SYNONYM to TMPSMSI_PUB;                                        
grant CREATE ROLE to TMPSMSI_PUB;                                                  
grant CREATE ROLLBACK SEGMENT to TMPSMSI_PUB;                                      
grant CREATE RULE SET to TMPSMSI_PUB;                                              
grant CREATE RULE to TMPSMSI_PUB;                                                  
grant CREATE SEQUENCE to TMPSMSI_PUB;                                              
grant CREATE SESSION to TMPSMSI_PUB;                                               
grant CREATE SYNONYM to TMPSMSI_PUB;                                               
grant CREATE TABLE to TMPSMSI_PUB;                                                 
grant CREATE TABLESPACE to TMPSMSI_PUB;                                            
grant CREATE TRIGGER to TMPSMSI_PUB;                                               
grant CREATE TYPE to TMPSMSI_PUB;                                                  
grant CREATE USER to TMPSMSI_PUB;                                                  
grant CREATE VIEW to TMPSMSI_PUB;                                                  
grant DEBUG ANY PROCEDURE to TMPSMSI_PUB;                                          
grant DEBUG CONNECT SESSION to TMPSMSI_PUB;                                        
grant DELETE ANY CUBE DIMENSION to TMPSMSI_PUB;                                    
grant DELETE ANY MEASURE FOLDER to TMPSMSI_PUB;                                    
grant DELETE ANY TABLE to TMPSMSI_PUB;                                             
grant DEQUEUE ANY QUEUE to TMPSMSI_PUB;                                            
grant DROP ANY ASSEMBLY to TMPSMSI_PUB;                                            
grant DROP ANY CLUSTER to TMPSMSI_PUB;                                             
grant DROP ANY CONTEXT to TMPSMSI_PUB;                                             
grant DROP ANY CUBE BUILD PROCESS to TMPSMSI_PUB;                                  
grant DROP ANY CUBE DIMENSION to TMPSMSI_PUB;                                      
grant DROP ANY CUBE to TMPSMSI_PUB;                                                
grant DROP ANY DIMENSION to TMPSMSI_PUB;                                           
grant DROP ANY DIRECTORY to TMPSMSI_PUB;                                           
grant DROP ANY EDITION to TMPSMSI_PUB;                                             
grant DROP ANY EVALUATION CONTEXT to TMPSMSI_PUB;                                  
grant DROP ANY INDEX to TMPSMSI_PUB;                                               
grant DROP ANY INDEXTYPE to TMPSMSI_PUB;                                           
grant DROP ANY LIBRARY to TMPSMSI_PUB;                                             
grant DROP ANY MATERIALIZED VIEW to TMPSMSI_PUB;                                   
grant DROP ANY MEASURE FOLDER to TMPSMSI_PUB;                                      
grant DROP ANY MINING MODEL to TMPSMSI_PUB;                                        
grant DROP ANY OPERATOR to TMPSMSI_PUB;                                            
grant DROP ANY OUTLINE to TMPSMSI_PUB;                                             
grant DROP ANY PROCEDURE to TMPSMSI_PUB;                                           
grant DROP ANY ROLE to TMPSMSI_PUB;                                                
grant DROP ANY RULE SET to TMPSMSI_PUB;                                            
grant DROP ANY RULE to TMPSMSI_PUB;                                                
grant DROP ANY SEQUENCE to TMPSMSI_PUB;                                            
grant DROP ANY SQL PROFILE to TMPSMSI_PUB;                                         
grant DROP ANY SYNONYM to TMPSMSI_PUB;                                             
grant DROP ANY TABLE to TMPSMSI_PUB;                                               
grant DROP ANY TRIGGER to TMPSMSI_PUB;                                             
grant DROP ANY TYPE to TMPSMSI_PUB;                                                
grant DROP ANY VIEW to TMPSMSI_PUB;                                                
grant DROP PROFILE to TMPSMSI_PUB;                                                 
grant DROP PUBLIC DATABASE LINK to TMPSMSI_PUB;                                    
grant DROP PUBLIC SYNONYM to TMPSMSI_PUB;                                          
grant DROP ROLLBACK SEGMENT to TMPSMSI_PUB;                                        
grant DROP TABLESPACE to TMPSMSI_PUB;                                              
grant DROP USER to TMPSMSI_PUB;                                                    
grant ENQUEUE ANY QUEUE to TMPSMSI_PUB;                                            
grant EXECUTE ANY ASSEMBLY to TMPSMSI_PUB;                                         
grant EXECUTE ANY CLASS to TMPSMSI_PUB;                                            
grant EXECUTE ANY EVALUATION CONTEXT to TMPSMSI_PUB;                               
grant EXECUTE ANY INDEXTYPE to TMPSMSI_PUB;                                        
grant EXECUTE ANY LIBRARY to TMPSMSI_PUB;                                          
grant EXECUTE ANY OPERATOR to TMPSMSI_PUB;                                         
grant EXECUTE ANY PROCEDURE to TMPSMSI_PUB;                                        
grant EXECUTE ANY PROGRAM to TMPSMSI_PUB;                                          
grant EXECUTE ANY RULE SET to TMPSMSI_PUB;                                         
grant EXECUTE ANY RULE to TMPSMSI_PUB;                                             
grant EXECUTE ANY TYPE to TMPSMSI_PUB;                                             
grant EXECUTE ASSEMBLY to TMPSMSI_PUB;                                             
grant EXEMPT ACCESS POLICY to TMPSMSI_PUB;                                         
grant EXEMPT IDENTITY POLICY to TMPSMSI_PUB;                                       
grant EXPORT FULL DATABASE to TMPSMSI_PUB;                                         
grant FLASHBACK ANY TABLE to TMPSMSI_PUB;                                          
grant FLASHBACK ARCHIVE ADMINISTER to TMPSMSI_PUB;                                 
grant FORCE ANY TRANSACTION to TMPSMSI_PUB;                                        
grant FORCE TRANSACTION to TMPSMSI_PUB;                                            
grant GLOBAL QUERY REWRITE to TMPSMSI_PUB;                                         
grant GRANT ANY OBJECT PRIVILEGE to TMPSMSI_PUB;                                   
grant GRANT ANY PRIVILEGE to TMPSMSI_PUB;                                          
grant GRANT ANY ROLE to TMPSMSI_PUB;                                               
grant IMPORT FULL DATABASE to TMPSMSI_PUB;                                         
grant INSERT ANY CUBE DIMENSION to TMPSMSI_PUB;                                    
grant INSERT ANY MEASURE FOLDER to TMPSMSI_PUB;                                    
grant INSERT ANY TABLE to TMPSMSI_PUB;                                             
grant LOCK ANY TABLE to TMPSMSI_PUB;                                               
grant MANAGE ANY FILE GROUP to TMPSMSI_PUB;                                        
grant MANAGE ANY QUEUE to TMPSMSI_PUB;                                             
grant MANAGE FILE GROUP to TMPSMSI_PUB;                                            
grant MANAGE SCHEDULER to TMPSMSI_PUB;                                             
grant MANAGE TABLESPACE to TMPSMSI_PUB;                                            
grant MERGE ANY VIEW to TMPSMSI_PUB;                                               
grant ON COMMIT REFRESH to TMPSMSI_PUB;                                            
grant QUERY REWRITE to TMPSMSI_PUB;                                                
grant READ ANY FILE GROUP to TMPSMSI_PUB;                                          
grant RESTRICTED SESSION to TMPSMSI_PUB;                                           
grant RESUMABLE to TMPSMSI_PUB;                                                    
grant SELECT ANY CUBE DIMENSION to TMPSMSI_PUB;                                    
grant SELECT ANY CUBE to TMPSMSI_PUB;                                              
grant SELECT ANY DICTIONARY to TMPSMSI_PUB;                                        
grant SELECT ANY MINING MODEL to TMPSMSI_PUB;                                      
grant SELECT ANY SEQUENCE to TMPSMSI_PUB;                                          
grant SELECT ANY TABLE to TMPSMSI_PUB;                                             
grant SELECT ANY TRANSACTION to TMPSMSI_PUB;                                       
grant UNDER ANY TABLE to TMPSMSI_PUB;                                              
grant UNDER ANY TYPE to TMPSMSI_PUB;                                               
grant UNDER ANY VIEW to TMPSMSI_PUB;                                               
grant UNLIMITED TABLESPACE to TMPSMSI_PUB;                                         
grant UPDATE ANY CUBE BUILD PROCESS to TMPSMSI_PUB;                                
grant UPDATE ANY CUBE DIMENSION to TMPSMSI_PUB;                                    
grant UPDATE ANY CUBE to TMPSMSI_PUB;                                              
grant UPDATE ANY TABLE to TMPSMSI_PUB;                                             
grant CONNECT to TMPSMSI_PUB;                                                      
grant RESOURCE to TMPSMSI_PUB;                                                     
