CREATE USER TMPPCI_PERF IDENTIFIED BY TMPPCI_PERF DEFAULT TABLESPACE canoe_data_compress
TEMPORARY TABLESPACE TEMP PROFILE DEFAULT ACCOUNT UNLOCK;

GRANT TABLE_OWNER TO TMPPCI_PERF; 
GRANT RESOURCE TO TMPPCI_PERF;
Grant create session, alter session to TMPPCI_PERF;
 
