CREATE USER DAIDCE IDENTIFIED BY DAIDCE;
ALTER USER DAIDCE QUOTA UNLIMITED ON CANOE_DATA;
ALTER USER DAIDCE QUOTA UNLIMITED ON CANOE_DATA_COMPRESS;
ALTER USER DAIDCE QUOTA UNLIMITED ON CANOE_DATA_COMPRESS2;
ALTER USER DAIDCE QUOTA UNLIMITED ON CANOE_INDEX;
GRANT TABLE_OWNER TO DAIDCE;
GRANT CONNECT, RESOURCE, CREATE ANY SYNONYM, CREATE VIEW, CREATE TRIGGER, CREATE ANY TRIGGER, CREATE MATERIALIZED VIEW, CREATE ANY MATERIALIZED VIEW, UNLIMITED TABLESPACE TO DAIDCE;
