CREATE USER TMPSMSI_RELAY_02 IDENTIFIED BY TMPSMSI_RELAY_02 DEFAULT TABLESPACE canoe_data_compress
TEMPORARY TABLESPACE TEMP PROFILE DEFAULT ACCOUNT UNLOCK;
 
GRANT SELECT ANY DICTIONARY TO TMPSMSI_RELAY_02;
GRANT ON COMMIT REFRESH TO TMPSMSI_RELAY_02;
GRANT GLOBAL QUERY REWRITE TO TMPSMSI_RELAY_02;
GRANT UNLIMITED TABLESPACE TO TMPSMSI_RELAY_02;
GRANT CREATE TRIGGER TO TMPSMSI_RELAY_02;
GRANT CREATE SESSION TO TMPSMSI_RELAY_02;
GRANT CREATE ANY JOB TO TMPSMSI_RELAY_02;
GRANT CREATE ANY MATERIALIZED VIEW TO TMPSMSI_RELAY_02;
GRANT CREATE SYNONYM TO TMPSMSI_RELAY_02;
GRANT CREATE MATERIALIZED VIEW TO TMPSMSI_RELAY_02;
GRANT CREATE TABLE TO TMPSMSI_RELAY_02;
GRANT CREATE VIEW TO TMPSMSI_RELAY_02;
GRANT CREATE SEQUENCE TO TMPSMSI_RELAY_02;
GRANT QUERY REWRITE TO TMPSMSI_RELAY_02;
GRANT CREATE JOB TO TMPSMSI_RELAY_02;
GRANT CREATE TYPE TO TMPSMSI_RELAY_02;
GRANT CREATE PROCEDURE TO TMPSMSI_RELAY_02;
GRANT SCHEDULER_ADMIN TO TMPSMSI_RELAY_02;
 
GRANT RESOURCE TO TMPSMSI_RELAY_02;
Grant create session, alter session to TMPSMSI_RELAY_02;
 
 
GRANT SELECT, REFERENCES ON TMPCAAS_CORE.PROGRAMMER TO TMPSMSI_RELAY_02;
GRANT SELECT, REFERENCES ON TMPCAAS_CORE.PROVIDER_NETWORK TO TMPSMSI_RELAY_02;
GRANT SELECT, REFERENCES ON TMPCAAS_CORE.NETWORK TO TMPSMSI_RELAY_02;
