GRANT FLASHBACK ARCHIVE ON audit_campaign TO CAAS_LOCAL;
GRANT FLASHBACK ARCHIVE ON audit_media_asset TO CAAS_LOCAL;
GRANT FLASHBACK ARCHIVE ON audit_campaign TO CAAS_CORE_FW;
GRANT FLASHBACK ARCHIVE ON audit_media_asset TO CAAS_CORE_FW;
GRANT FLASHBACK ARCHIVE ON audit_campaign TO CAAS40;
GRANT FLASHBACK ARCHIVE ON audit_media_asset TO CAAS40;
