CREATE USER REQMAN IDENTIFIED BY REQMAN DEFAULT TABLESPACE canoe_data_compress
TEMPORARY TABLESPACE TEMP PROFILE DEFAULT ACCOUNT UNLOCK;

ALTER USER REQMAN QUOTA UNLIMITED ON CANOE_DATA_COMPRESS;
ALTER USER REQMAN QUOTA UNLIMITED ON CANOE_DATA;
ALTER USER REQMAN QUOTA UNLIMITED ON CANOE_INDEX;
GRANT resource, create session, create table, create sequence, DBA, scheduler_admin to REQMAN;
grant select on CAAS40.MEDIA_ASSET to REQMAN;
