CREATE USER SMSI_RELAY_BRD IDENTIFIED BY SMSI_RELAY_BRD DEFAULT TABLESPACE canoe_data_compress
TEMPORARY TABLESPACE TEMP PROFILE DEFAULT ACCOUNT UNLOCK;

GRANT SELECT ANY DICTIONARY TO SMSI_RELAY_BRD;
GRANT ON COMMIT REFRESH TO SMSI_RELAY_BRD;
GRANT GLOBAL QUERY REWRITE TO SMSI_RELAY_BRD;
GRANT UNLIMITED TABLESPACE TO SMSI_RELAY_BRD;
GRANT CREATE TRIGGER TO SMSI_RELAY_BRD;
GRANT CREATE SESSION TO SMSI_RELAY_BRD;
GRANT CREATE ANY JOB TO SMSI_RELAY_BRD;
GRANT CREATE ANY MATERIALIZED VIEW TO SMSI_RELAY_BRD;
GRANT CREATE SYNONYM TO SMSI_RELAY_BRD;
GRANT CREATE MATERIALIZED VIEW TO SMSI_RELAY_BRD;
GRANT CREATE TABLE TO SMSI_RELAY_BRD;
GRANT CREATE VIEW TO SMSI_RELAY_BRD;
GRANT CREATE SEQUENCE TO SMSI_RELAY_BRD;
GRANT QUERY REWRITE TO SMSI_RELAY_BRD;
GRANT CREATE JOB TO SMSI_RELAY_BRD;
GRANT CREATE TYPE TO SMSI_RELAY_BRD;
GRANT CREATE PROCEDURE TO SMSI_RELAY_BRD;
GRANT SCHEDULER_ADMIN TO SMSI_RELAY_BRD;

GRANT RESOURCE TO SMSI_RELAY_BRD;
Grant create session, alter session to SMSI_RELAY_BRD;


GRANT SELECT, REFERENCES ON CAAS_CORE_BRD.PROGRAMMER TO SMSI_RELAY_BRD;
GRANT SELECT, REFERENCES ON CAAS_CORE_BRD.PROVIDER_NETWORK TO SMSI_RELAY_BRD;
GRANT SELECT, REFERENCES ON CAAS_CORE_BRD.NETWORK TO SMSI_RELAY_BRD;
