CREATE USER PCI_BRD IDENTIFIED BY PCI_BRD DEFAULT TABLESPACE canoe_data_compress
TEMPORARY TABLESPACE TEMP PROFILE DEFAULT ACCOUNT UNLOCK;

GRANT TABLE_OWNER TO PCI_BRD; 
GRANT RESOURCE TO PCI_BRD;
Grant create session, alter session to PCI_BRD;
 
