create user REMA_PUB_CMC identified by REMA_PUB_CMC                                     
default tablespace canoe_data                                                   
quota unlimited on canoe_data                                                   
quota unlimited on canoe_index                                                  
quota unlimited on canoe_data_compress                                          
/                                                                               
                                                                                
grant ADMINISTER ANY SQL TUNING SET to REMA_PUB_CMC;                                
grant ADMINISTER DATABASE TRIGGER to REMA_PUB_CMC;                                  
grant ADMINISTER RESOURCE MANAGER to REMA_PUB_CMC;                                  
grant ADMINISTER SQL MANAGEMENT OBJECT to REMA_PUB_CMC;                             
grant ADMINISTER SQL TUNING SET to REMA_PUB_CMC;                                    
grant ADVISOR to REMA_PUB_CMC;                                                      
grant ALTER ANY ASSEMBLY to REMA_PUB_CMC;                                           
grant ALTER ANY CLUSTER to REMA_PUB_CMC;                                            
grant ALTER ANY CUBE DIMENSION to REMA_PUB_CMC;                                     
grant ALTER ANY CUBE to REMA_PUB_CMC;                                               
grant ALTER ANY DIMENSION to REMA_PUB_CMC;                                          
grant ALTER ANY EDITION to REMA_PUB_CMC;                                            
grant ALTER ANY EVALUATION CONTEXT to REMA_PUB_CMC;                                 
grant ALTER ANY INDEX to REMA_PUB_CMC;                                              
grant ALTER ANY INDEXTYPE to REMA_PUB_CMC;                                          
grant ALTER ANY LIBRARY to REMA_PUB_CMC;                                            
grant ALTER ANY MATERIALIZED VIEW to REMA_PUB_CMC;                                  
grant ALTER ANY MINING MODEL to REMA_PUB_CMC;                                       
grant ALTER ANY OPERATOR to REMA_PUB_CMC;                                           
grant ALTER ANY OUTLINE to REMA_PUB_CMC;                                            
grant ALTER ANY PROCEDURE to REMA_PUB_CMC;                                          
grant ALTER ANY ROLE to REMA_PUB_CMC;                                               
grant ALTER ANY RULE SET to REMA_PUB_CMC;                                           
grant ALTER ANY RULE to REMA_PUB_CMC;                                               
grant ALTER ANY SEQUENCE to REMA_PUB_CMC;                                           
grant ALTER ANY SQL PROFILE to REMA_PUB_CMC;                                        
grant ALTER ANY TABLE to REMA_PUB_CMC;                                              
grant ALTER ANY TRIGGER to REMA_PUB_CMC;                                            
grant ALTER ANY TYPE to REMA_PUB_CMC;                                               
grant ALTER DATABASE LINK to REMA_PUB_CMC;                                          
grant ALTER DATABASE to REMA_PUB_CMC;                                               
grant ALTER PROFILE to REMA_PUB_CMC;                                                
grant ALTER PUBLIC DATABASE LINK to REMA_PUB_CMC;                                   
grant ALTER RESOURCE COST to REMA_PUB_CMC;                                          
grant ALTER ROLLBACK SEGMENT to REMA_PUB_CMC;                                       
grant ALTER SESSION to REMA_PUB_CMC;                                                
grant ALTER SYSTEM to REMA_PUB_CMC;                                                 
grant ALTER TABLESPACE to REMA_PUB_CMC;                                             
grant ALTER USER to REMA_PUB_CMC;                                                   
grant ANALYZE ANY DICTIONARY to REMA_PUB_CMC;                                       
grant ANALYZE ANY to REMA_PUB_CMC;                                                  
grant AUDIT ANY to REMA_PUB_CMC;                                                    
grant AUDIT SYSTEM to REMA_PUB_CMC;                                                 
grant BACKUP ANY TABLE to REMA_PUB_CMC;                                             
grant BECOME USER to REMA_PUB_CMC;                                                  
grant CHANGE NOTIFICATION to REMA_PUB_CMC;                                          
grant COMMENT ANY MINING MODEL to REMA_PUB_CMC;                                     
grant COMMENT ANY TABLE to REMA_PUB_CMC;                                            
grant CREATE ANY ASSEMBLY to REMA_PUB_CMC;                                          
grant CREATE ANY CLUSTER to REMA_PUB_CMC;                                           
grant CREATE ANY CONTEXT to REMA_PUB_CMC;                                           
grant CREATE ANY CUBE BUILD PROCESS to REMA_PUB_CMC;                                
grant CREATE ANY CUBE DIMENSION to REMA_PUB_CMC;                                    
grant CREATE ANY CUBE to REMA_PUB_CMC;                                              
grant CREATE ANY DIMENSION to REMA_PUB_CMC;                                         
grant CREATE ANY DIRECTORY to REMA_PUB_CMC;                                         
grant CREATE ANY EDITION to REMA_PUB_CMC;                                           
grant CREATE ANY EVALUATION CONTEXT to REMA_PUB_CMC;                                
grant CREATE ANY INDEX to REMA_PUB_CMC;                                             
grant CREATE ANY INDEXTYPE to REMA_PUB_CMC;                                         
grant CREATE ANY JOB to REMA_PUB_CMC;                                               
grant CREATE ANY LIBRARY to REMA_PUB_CMC;                                           
grant CREATE ANY MATERIALIZED VIEW to REMA_PUB_CMC;                                 
grant CREATE ANY MEASURE FOLDER to REMA_PUB_CMC;                                    
grant CREATE ANY MINING MODEL to REMA_PUB_CMC;                                      
grant CREATE ANY OPERATOR to REMA_PUB_CMC;                                          
grant CREATE ANY OUTLINE to REMA_PUB_CMC;                                           
grant CREATE ANY PROCEDURE to REMA_PUB_CMC;                                         
grant CREATE ANY RULE SET to REMA_PUB_CMC;                                          
grant CREATE ANY RULE to REMA_PUB_CMC;                                              
grant CREATE ANY SEQUENCE to REMA_PUB_CMC;                                          
grant CREATE ANY SQL PROFILE to REMA_PUB_CMC;                                       
grant CREATE ANY SYNONYM to REMA_PUB_CMC;                                           
grant CREATE ANY TABLE to REMA_PUB_CMC;                                             
grant CREATE ANY TRIGGER to REMA_PUB_CMC;                                           
grant CREATE ANY TYPE to REMA_PUB_CMC;                                              
grant CREATE ANY VIEW to REMA_PUB_CMC;                                              
grant CREATE ASSEMBLY to REMA_PUB_CMC;                                              
grant CREATE CLUSTER to REMA_PUB_CMC;                                               
grant CREATE CUBE BUILD PROCESS to REMA_PUB_CMC;                                    
grant CREATE CUBE DIMENSION to REMA_PUB_CMC;                                        
grant CREATE CUBE to REMA_PUB_CMC;                                                  
grant CREATE DATABASE LINK to REMA_PUB_CMC;                                         
grant CREATE DIMENSION to REMA_PUB_CMC;                                             
grant CREATE EVALUATION CONTEXT to REMA_PUB_CMC;                                    
grant CREATE EXTERNAL JOB to REMA_PUB_CMC;                                          
grant CREATE INDEXTYPE to REMA_PUB_CMC;                                             
grant CREATE JOB to REMA_PUB_CMC;                                                   
grant CREATE LIBRARY to REMA_PUB_CMC;                                               
grant CREATE MATERIALIZED VIEW to REMA_PUB_CMC;                                     
grant CREATE MEASURE FOLDER to REMA_PUB_CMC;                                        
grant CREATE MINING MODEL to REMA_PUB_CMC;                                          
grant CREATE OPERATOR to REMA_PUB_CMC;                                              
grant CREATE PROCEDURE to REMA_PUB_CMC;                                             
grant CREATE PROFILE to REMA_PUB_CMC;                                               
grant CREATE PUBLIC DATABASE LINK to REMA_PUB_CMC;                                  
grant CREATE PUBLIC SYNONYM to REMA_PUB_CMC;                                        
grant CREATE ROLE to REMA_PUB_CMC;                                                  
grant CREATE ROLLBACK SEGMENT to REMA_PUB_CMC;                                      
grant CREATE RULE SET to REMA_PUB_CMC;                                              
grant CREATE RULE to REMA_PUB_CMC;                                                  
grant CREATE SEQUENCE to REMA_PUB_CMC;                                              
grant CREATE SESSION to REMA_PUB_CMC;                                               
grant CREATE SYNONYM to REMA_PUB_CMC;                                               
grant CREATE TABLE to REMA_PUB_CMC;                                                 
grant CREATE TABLESPACE to REMA_PUB_CMC;                                            
grant CREATE TRIGGER to REMA_PUB_CMC;                                               
grant CREATE TYPE to REMA_PUB_CMC;                                                  
grant CREATE USER to REMA_PUB_CMC;                                                  
grant CREATE VIEW to REMA_PUB_CMC;                                                  
grant DEBUG ANY PROCEDURE to REMA_PUB_CMC;                                          
grant DEBUG CONNECT SESSION to REMA_PUB_CMC;                                        
grant DELETE ANY CUBE DIMENSION to REMA_PUB_CMC;                                    
grant DELETE ANY MEASURE FOLDER to REMA_PUB_CMC;                                    
grant DELETE ANY TABLE to REMA_PUB_CMC;                                             
grant DEQUEUE ANY QUEUE to REMA_PUB_CMC;                                            
grant DROP ANY ASSEMBLY to REMA_PUB_CMC;                                            
grant DROP ANY CLUSTER to REMA_PUB_CMC;                                             
grant DROP ANY CONTEXT to REMA_PUB_CMC;                                             
grant DROP ANY CUBE BUILD PROCESS to REMA_PUB_CMC;                                  
grant DROP ANY CUBE DIMENSION to REMA_PUB_CMC;                                      
grant DROP ANY CUBE to REMA_PUB_CMC;                                                
grant DROP ANY DIMENSION to REMA_PUB_CMC;                                           
grant DROP ANY DIRECTORY to REMA_PUB_CMC;                                           
grant DROP ANY EDITION to REMA_PUB_CMC;                                             
grant DROP ANY EVALUATION CONTEXT to REMA_PUB_CMC;                                  
grant DROP ANY INDEX to REMA_PUB_CMC;                                               
grant DROP ANY INDEXTYPE to REMA_PUB_CMC;                                           
grant DROP ANY LIBRARY to REMA_PUB_CMC;                                             
grant DROP ANY MATERIALIZED VIEW to REMA_PUB_CMC;                                   
grant DROP ANY MEASURE FOLDER to REMA_PUB_CMC;                                      
grant DROP ANY MINING MODEL to REMA_PUB_CMC;                                        
grant DROP ANY OPERATOR to REMA_PUB_CMC;                                            
grant DROP ANY OUTLINE to REMA_PUB_CMC;                                             
grant DROP ANY PROCEDURE to REMA_PUB_CMC;                                           
grant DROP ANY ROLE to REMA_PUB_CMC;                                                
grant DROP ANY RULE SET to REMA_PUB_CMC;                                            
grant DROP ANY RULE to REMA_PUB_CMC;                                                
grant DROP ANY SEQUENCE to REMA_PUB_CMC;                                            
grant DROP ANY SQL PROFILE to REMA_PUB_CMC;                                         
grant DROP ANY SYNONYM to REMA_PUB_CMC;                                             
grant DROP ANY TABLE to REMA_PUB_CMC;                                               
grant DROP ANY TRIGGER to REMA_PUB_CMC;                                             
grant DROP ANY TYPE to REMA_PUB_CMC;                                                
grant DROP ANY VIEW to REMA_PUB_CMC;                                                
grant DROP PROFILE to REMA_PUB_CMC;                                                 
grant DROP PUBLIC DATABASE LINK to REMA_PUB_CMC;                                    
grant DROP PUBLIC SYNONYM to REMA_PUB_CMC;                                          
grant DROP ROLLBACK SEGMENT to REMA_PUB_CMC;                                        
grant DROP TABLESPACE to REMA_PUB_CMC;                                              
grant DROP USER to REMA_PUB_CMC;                                                    
grant ENQUEUE ANY QUEUE to REMA_PUB_CMC;                                            
grant EXECUTE ANY ASSEMBLY to REMA_PUB_CMC;                                         
grant EXECUTE ANY CLASS to REMA_PUB_CMC;                                            
grant EXECUTE ANY EVALUATION CONTEXT to REMA_PUB_CMC;                               
grant EXECUTE ANY INDEXTYPE to REMA_PUB_CMC;                                        
grant EXECUTE ANY LIBRARY to REMA_PUB_CMC;                                          
grant EXECUTE ANY OPERATOR to REMA_PUB_CMC;                                         
grant EXECUTE ANY PROCEDURE to REMA_PUB_CMC;                                        
grant EXECUTE ANY PROGRAM to REMA_PUB_CMC;                                          
grant EXECUTE ANY RULE SET to REMA_PUB_CMC;                                         
grant EXECUTE ANY RULE to REMA_PUB_CMC;                                             
grant EXECUTE ANY TYPE to REMA_PUB_CMC;                                             
grant EXECUTE ASSEMBLY to REMA_PUB_CMC;                                             
grant EXEMPT ACCESS POLICY to REMA_PUB_CMC;                                         
grant EXEMPT IDENTITY POLICY to REMA_PUB_CMC;                                       
grant EXPORT FULL DATABASE to REMA_PUB_CMC;                                         
grant FLASHBACK ANY TABLE to REMA_PUB_CMC;                                          
grant FLASHBACK ARCHIVE ADMINISTER to REMA_PUB_CMC;                                 
grant FORCE ANY TRANSACTION to REMA_PUB_CMC;                                        
grant FORCE TRANSACTION to REMA_PUB_CMC;                                            
grant GLOBAL QUERY REWRITE to REMA_PUB_CMC;                                         
grant GRANT ANY OBJECT PRIVILEGE to REMA_PUB_CMC;                                   
grant GRANT ANY PRIVILEGE to REMA_PUB_CMC;                                          
grant GRANT ANY ROLE to REMA_PUB_CMC;                                               
grant IMPORT FULL DATABASE to REMA_PUB_CMC;                                         
grant INSERT ANY CUBE DIMENSION to REMA_PUB_CMC;                                    
grant INSERT ANY MEASURE FOLDER to REMA_PUB_CMC;                                    
grant INSERT ANY TABLE to REMA_PUB_CMC;                                             
grant LOCK ANY TABLE to REMA_PUB_CMC;                                               
grant MANAGE ANY FILE GROUP to REMA_PUB_CMC;                                        
grant MANAGE ANY QUEUE to REMA_PUB_CMC;                                             
grant MANAGE FILE GROUP to REMA_PUB_CMC;                                            
grant MANAGE SCHEDULER to REMA_PUB_CMC;                                             
grant MANAGE TABLESPACE to REMA_PUB_CMC;                                            
grant MERGE ANY VIEW to REMA_PUB_CMC;                                               
grant ON COMMIT REFRESH to REMA_PUB_CMC;                                            
grant QUERY REWRITE to REMA_PUB_CMC;                                                
grant READ ANY FILE GROUP to REMA_PUB_CMC;                                          
grant RESTRICTED SESSION to REMA_PUB_CMC;                                           
grant RESUMABLE to REMA_PUB_CMC;                                                    
grant SELECT ANY CUBE DIMENSION to REMA_PUB_CMC;                                    
grant SELECT ANY CUBE to REMA_PUB_CMC;                                              
grant SELECT ANY DICTIONARY to REMA_PUB_CMC;                                        
grant SELECT ANY MINING MODEL to REMA_PUB_CMC;                                      
grant SELECT ANY SEQUENCE to REMA_PUB_CMC;                                          
grant SELECT ANY TABLE to REMA_PUB_CMC;                                             
grant SELECT ANY TRANSACTION to REMA_PUB_CMC;                                       
grant UNDER ANY TABLE to REMA_PUB_CMC;                                              
grant UNDER ANY TYPE to REMA_PUB_CMC;                                               
grant UNDER ANY VIEW to REMA_PUB_CMC;                                               
grant UNLIMITED TABLESPACE to REMA_PUB_CMC;                                         
grant UPDATE ANY CUBE BUILD PROCESS to REMA_PUB_CMC;                                
grant UPDATE ANY CUBE DIMENSION to REMA_PUB_CMC;                                    
grant UPDATE ANY CUBE to REMA_PUB_CMC;                                              
grant UPDATE ANY TABLE to REMA_PUB_CMC;                                             
grant CONNECT to REMA_PUB_CMC;                                                      
grant RESOURCE to REMA_PUB_CMC;                                                     
