CREATE USER PCI_KODIAK IDENTIFIED BY PCI_KODIAK DEFAULT TABLESPACE canoe_data_compress
TEMPORARY TABLESPACE TEMP PROFILE DEFAULT ACCOUNT UNLOCK;

GRANT TABLE_OWNER TO PCI_KODIAK; 
GRANT RESOURCE TO PCI_KODIAK;
Grant create session, alter session to PCI_KODIAK;
 
