CREATE USER MAR_REMA IDENTIFIED BY MAR_REMA DEFAULT TABLESPACE canoe_data_compress
TEMPORARY TABLESPACE TEMP PROFILE DEFAULT ACCOUNT UNLOCK;

ALTER USER MAR_REMA QUOTA UNLIMITED ON CANOE_DATA_COMPRESS;
ALTER USER MAR_REMA QUOTA UNLIMITED ON CANOE_DATA;
ALTER USER MAR_REMA QUOTA UNLIMITED ON CANOE_INDEX;
GRANT resource, create session, create table, create sequence, DBA, scheduler_admin to MAR_REMA;
