CREATE USER SC1_REMA IDENTIFIED BY SC1_REMA DEFAULT TABLESPACE canoe_data_compress
TEMPORARY TABLESPACE TEMP PROFILE DEFAULT ACCOUNT UNLOCK;

ALTER USER SC1_REMA QUOTA UNLIMITED ON CANOE_DATA_COMPRESS;
ALTER USER SC1_REMA QUOTA UNLIMITED ON CANOE_DATA;
ALTER USER SC1_REMA QUOTA UNLIMITED ON CANOE_INDEX;
GRANT resource, create session, create table, create sequence, DBA, scheduler_admin to SC1_REMA;
