CREATE USER DI_REMA IDENTIFIED BY DI_REMA DEFAULT TABLESPACE canoe_data_compress
TEMPORARY TABLESPACE TEMP PROFILE DEFAULT ACCOUNT UNLOCK;

ALTER USER DI_REMA QUOTA UNLIMITED ON CANOE_DATA_COMPRESS;
ALTER USER DI_REMA QUOTA UNLIMITED ON CANOE_DATA;
ALTER USER DI_REMA QUOTA UNLIMITED ON CANOE_INDEX;
GRANT resource, create session, create table, create sequence, DBA, scheduler_admin to DI_REMA;
