create user CAAS40 identified by CAAS40                                   
default tablespace canoe_data                                                   
quota unlimited on canoe_data                                                   
quota unlimited on canoe_index                                                  
quota unlimited on canoe_data_compress                                          
/                                                                               
                                                                                
grant ADMINISTER ANY SQL TUNING SET to CAAS40;                               
grant ADMINISTER DATABASE TRIGGER to CAAS40;                                 
grant ADMINISTER SQL MANAGEMENT OBJECT to CAAS40;                            
grant ADMINISTER SQL TUNING SET to CAAS40;                                   
grant ADVISOR to CAAS40;                                                     
grant ALTER ANY ASSEMBLY to CAAS40;                                          
grant ALTER ANY CLUSTER to CAAS40;                                           
grant ALTER ANY CUBE DIMENSION to CAAS40;                                    
grant ALTER ANY CUBE to CAAS40;                                              
grant ALTER ANY DIMENSION to CAAS40;                                         
grant ALTER ANY EDITION to CAAS40;                                           
grant ALTER ANY INDEX to CAAS40;                                             
grant ALTER ANY INDEXTYPE to CAAS40;                                         
grant ALTER ANY LIBRARY to CAAS40;                                           
grant ALTER ANY MATERIALIZED VIEW to CAAS40;                                 
grant ALTER ANY MINING MODEL to CAAS40;                                      
grant ALTER ANY OPERATOR to CAAS40;                                          
grant ALTER ANY OUTLINE to CAAS40;                                           
grant ALTER ANY PROCEDURE to CAAS40;                                         
grant ALTER ANY ROLE to CAAS40;                                              
grant ALTER ANY SEQUENCE to CAAS40;                                          
grant ALTER ANY SQL PROFILE to CAAS40;                                       
grant ALTER ANY TABLE to CAAS40;                                             
grant ALTER ANY TRIGGER to CAAS40;                                           
grant ALTER ANY TYPE to CAAS40;                                              
grant ALTER DATABASE LINK to CAAS40;                                         
grant ALTER DATABASE to CAAS40;                                              
grant ALTER PROFILE to CAAS40;                                               
grant ALTER PUBLIC DATABASE LINK to CAAS40;                                  
grant ALTER RESOURCE COST to CAAS40;                                         
grant ALTER ROLLBACK SEGMENT to CAAS40;                                      
grant ALTER SESSION to CAAS40;                                               
grant ALTER SYSTEM to CAAS40;                                                
grant ALTER TABLESPACE to CAAS40;                                            
grant ALTER USER to CAAS40;                                                  
grant ANALYZE ANY DICTIONARY to CAAS40;                                      
grant ANALYZE ANY to CAAS40;                                                 
grant AUDIT ANY to CAAS40;                                                   
grant AUDIT SYSTEM to CAAS40;                                                
grant BACKUP ANY TABLE to CAAS40;                                            
grant BECOME USER to CAAS40;                                                 
grant CHANGE NOTIFICATION to CAAS40;                                         
grant COMMENT ANY MINING MODEL to CAAS40;                                    
grant COMMENT ANY TABLE to CAAS40;                                           
grant CREATE ANY ASSEMBLY to CAAS40;                                         
grant CREATE ANY CLUSTER to CAAS40;                                          
grant CREATE ANY CONTEXT to CAAS40;                                          
grant CREATE ANY CUBE BUILD PROCESS to CAAS40;                               
grant CREATE ANY CUBE DIMENSION to CAAS40;                                   
grant CREATE ANY CUBE to CAAS40;                                             
grant CREATE ANY DIMENSION to CAAS40;                                        
grant CREATE ANY DIRECTORY to CAAS40;                                        
grant CREATE ANY EDITION to CAAS40;                                          
grant CREATE ANY INDEX to CAAS40;                                            
grant CREATE ANY INDEXTYPE to CAAS40;                                        
grant CREATE ANY JOB to CAAS40;                                              
grant CREATE ANY LIBRARY to CAAS40;                                          
grant CREATE ANY MATERIALIZED VIEW to CAAS40;                                
grant CREATE ANY MEASURE FOLDER to CAAS40;                                   
grant CREATE ANY MINING MODEL to CAAS40;                                     
grant CREATE ANY OPERATOR to CAAS40;                                         
grant CREATE ANY OUTLINE to CAAS40;                                          
grant CREATE ANY PROCEDURE to CAAS40;                                        
grant CREATE ANY SEQUENCE to CAAS40;                                         
grant CREATE ANY SQL PROFILE to CAAS40;                                      
grant CREATE ANY SYNONYM to CAAS40;                                          
grant CREATE ANY TABLE to CAAS40;                                            
grant CREATE ANY TRIGGER to CAAS40;                                          
grant CREATE ANY TYPE to CAAS40;                                             
grant CREATE ANY VIEW to CAAS40;                                             
grant CREATE ASSEMBLY to CAAS40;                                             
grant CREATE CLUSTER to CAAS40;                                              
grant CREATE CUBE BUILD PROCESS to CAAS40;                                   
grant CREATE CUBE DIMENSION to CAAS40;                                       
grant CREATE CUBE to CAAS40;                                                 
grant CREATE DATABASE LINK to CAAS40;                                        
grant CREATE DIMENSION to CAAS40;                                            
grant CREATE EXTERNAL JOB to CAAS40;                                         
grant CREATE INDEXTYPE to CAAS40;                                            
grant CREATE JOB to CAAS40;                                                  
grant CREATE LIBRARY to CAAS40;                                              
grant CREATE MATERIALIZED VIEW to CAAS40;                                    
grant CREATE MEASURE FOLDER to CAAS40;                                       
grant CREATE MINING MODEL to CAAS40;                                         
grant CREATE OPERATOR to CAAS40;                                             
grant CREATE PROCEDURE to CAAS40;                                            
grant CREATE PROFILE to CAAS40;                                              
grant CREATE PUBLIC DATABASE LINK to CAAS40;                                 
grant CREATE PUBLIC SYNONYM to CAAS40;                                       
grant CREATE ROLE to CAAS40;                                                 
grant CREATE ROLLBACK SEGMENT to CAAS40;                                     
grant CREATE SEQUENCE to CAAS40;                                             
grant CREATE SESSION to CAAS40;                                              
grant CREATE SYNONYM to CAAS40;                                              
grant CREATE TABLE to CAAS40;                                                
grant CREATE TABLESPACE to CAAS40;                                           
grant CREATE TRIGGER to CAAS40;                                              
grant CREATE TYPE to CAAS40;                                                 
grant CREATE USER to CAAS40;                                                 
grant CREATE VIEW to CAAS40;                                                 
grant DEBUG ANY PROCEDURE to CAAS40;                                         
grant DEBUG CONNECT SESSION to CAAS40;                                       
grant DELETE ANY CUBE DIMENSION to CAAS40;                                   
grant DELETE ANY MEASURE FOLDER to CAAS40;                                   
grant DELETE ANY TABLE to CAAS40;                                            
grant DROP ANY ASSEMBLY to CAAS40;                                           
grant DROP ANY CLUSTER to CAAS40;                                            
grant DROP ANY CONTEXT to CAAS40;                                            
grant DROP ANY CUBE BUILD PROCESS to CAAS40;                                 
grant DROP ANY CUBE DIMENSION to CAAS40;                                     
grant DROP ANY CUBE to CAAS40;                                               
grant DROP ANY DIMENSION to CAAS40;                                          
grant DROP ANY DIRECTORY to CAAS40;                                          
grant DROP ANY EDITION to CAAS40;                                            
grant DROP ANY INDEX to CAAS40;                                              
grant DROP ANY INDEXTYPE to CAAS40;                                          
grant DROP ANY LIBRARY to CAAS40;                                            
grant DROP ANY MATERIALIZED VIEW to CAAS40;                                  
grant DROP ANY MEASURE FOLDER to CAAS40;                                     
grant DROP ANY MINING MODEL to CAAS40;                                       
grant DROP ANY OPERATOR to CAAS40;                                           
grant DROP ANY OUTLINE to CAAS40;                                            
grant DROP ANY PROCEDURE to CAAS40;                                          
grant DROP ANY ROLE to CAAS40;                                               
grant DROP ANY SEQUENCE to CAAS40;                                           
grant DROP ANY SQL PROFILE to CAAS40;                                        
grant DROP ANY SYNONYM to CAAS40;                                            
grant DROP ANY TABLE to CAAS40;                                              
grant DROP ANY TRIGGER to CAAS40;                                            
grant DROP ANY TYPE to CAAS40;                                               
grant DROP ANY VIEW to CAAS40;                                               
grant DROP PROFILE to CAAS40;                                                
grant DROP PUBLIC DATABASE LINK to CAAS40;                                   
grant DROP PUBLIC SYNONYM to CAAS40;                                         
grant DROP ROLLBACK SEGMENT to CAAS40;                                       
grant DROP TABLESPACE to CAAS40;                                             
grant DROP USER to CAAS40;                                                   
grant EXECUTE ANY ASSEMBLY to CAAS40;                                        
grant EXECUTE ANY CLASS to CAAS40;                                           
grant EXECUTE ANY INDEXTYPE to CAAS40;                                       
grant EXECUTE ANY LIBRARY to CAAS40;                                         
grant EXECUTE ANY OPERATOR to CAAS40;                                        
grant EXECUTE ANY PROCEDURE to CAAS40;                                       
grant EXECUTE ANY PROGRAM to CAAS40;                                         
grant EXECUTE ANY TYPE to CAAS40;                                            
grant EXECUTE ASSEMBLY to CAAS40;                                            
grant EXEMPT ACCESS POLICY to CAAS40;                                        
grant EXEMPT IDENTITY POLICY to CAAS40;                                      
grant EXPORT FULL DATABASE to CAAS40;                                        
grant FLASHBACK ANY TABLE to CAAS40;                                         
grant FLASHBACK ARCHIVE ADMINISTER to CAAS40;                                
grant FORCE ANY TRANSACTION to CAAS40;                                       
grant FORCE TRANSACTION to CAAS40;                                           
grant GLOBAL QUERY REWRITE to CAAS40;                                        
grant GRANT ANY OBJECT PRIVILEGE to CAAS40;                                  
grant GRANT ANY PRIVILEGE to CAAS40;                                         
grant GRANT ANY ROLE to CAAS40;                                              
grant IMPORT FULL DATABASE to CAAS40;                                        
grant INSERT ANY CUBE DIMENSION to CAAS40;                                   
grant INSERT ANY MEASURE FOLDER to CAAS40;                                   
grant INSERT ANY TABLE to CAAS40;                                            
grant LOCK ANY TABLE to CAAS40;                                              
grant MANAGE SCHEDULER to CAAS40;                                            
grant MANAGE TABLESPACE to CAAS40;                                           
grant MERGE ANY VIEW to CAAS40;                                              
grant ON COMMIT REFRESH to CAAS40;                                           
grant QUERY REWRITE to CAAS40;                                               
grant RESTRICTED SESSION to CAAS40;                                          
grant RESUMABLE to CAAS40;                                                   
grant SELECT ANY CUBE DIMENSION to CAAS40;                                   
grant SELECT ANY CUBE to CAAS40;                                             
grant SELECT ANY DICTIONARY to CAAS40;                                       
grant SELECT ANY MINING MODEL to CAAS40;                                     
grant SELECT ANY SEQUENCE to CAAS40;                                         
grant SELECT ANY TABLE to CAAS40;                                            
grant SELECT ANY TRANSACTION to CAAS40;                                      
grant UNDER ANY TABLE to CAAS40;                                             
grant UNDER ANY TYPE to CAAS40;                                              
grant UNDER ANY VIEW to CAAS40;                                              
grant UPDATE ANY CUBE BUILD PROCESS to CAAS40;                               
grant UPDATE ANY CUBE DIMENSION to CAAS40;                                   
grant UPDATE ANY CUBE to CAAS40;                                             
grant UPDATE ANY TABLE to CAAS40;                                            
CREATE FLASHBACK ARCHIVE audit_campaign TABLESPACE canoe_audit QUOTA 2G RETENTION 24 MONTH;
CREATE FLASHBACK ARCHIVE audit_media_asset TABLESPACE canoe_audit QUOTA 2G RETENTION 24 MONTH;
GRANT FLASHBACK ARCHIVE ON audit_campaign TO CAAS40;
GRANT FLASHBACK ARCHIVE ON audit_media_asset TO CAAS40;
GRANT FLASHBACK ARCHIVE ON audit_campaign TO CAAS_LOCAL;
GRANT FLASHBACK ARCHIVE ON audit_media_asset TO CAAS_LOCAL;
GRANT FLASHBACK ARCHIVE ON audit_campaign TO CAAS_CORE_FW;
GRANT FLASHBACK ARCHIVE ON audit_media_asset TO CAAS_CORE_FW;
GRANT FLASHBACK ARCHIVE ON audit_campaign TO CAAS_CORE_BRD;
GRANT FLASHBACK ARCHIVE ON audit_media_asset TO CAAS_CORE_BRD;
