create user CAAS_CORE_FW identified by BROADWAY 
default tablespace canoe_data                                                   
quota unlimited on canoe_data                                                   
quota unlimited on canoe_index                                                  
quota unlimited on canoe_data_compress                                          
/                                                                               
                                                                                
grant ADMINISTER ANY SQL TUNING SET to CAAS_CORE_FW;                               
grant ADMINISTER DATABASE TRIGGER to CAAS_CORE_FW;                                 
grant ADMINISTER SQL MANAGEMENT OBJECT to CAAS_CORE_FW;                            
grant ADMINISTER SQL TUNING SET to CAAS_CORE_FW;                                   
grant ADVISOR to CAAS_CORE_FW;                                                     
grant ALTER ANY ASSEMBLY to CAAS_CORE_FW;                                          
grant ALTER ANY CLUSTER to CAAS_CORE_FW;                                           
grant ALTER ANY CUBE DIMENSION to CAAS_CORE_FW;                                    
grant ALTER ANY CUBE to CAAS_CORE_FW;                                              
grant ALTER ANY DIMENSION to CAAS_CORE_FW;                                         
grant ALTER ANY EDITION to CAAS_CORE_FW;                                           
grant ALTER ANY INDEX to CAAS_CORE_FW;                                             
grant ALTER ANY INDEXTYPE to CAAS_CORE_FW;                                         
grant ALTER ANY LIBRARY to CAAS_CORE_FW;                                           
grant ALTER ANY MATERIALIZED VIEW to CAAS_CORE_FW;                                 
grant ALTER ANY MINING MODEL to CAAS_CORE_FW;                                      
grant ALTER ANY OPERATOR to CAAS_CORE_FW;                                          
grant ALTER ANY OUTLINE to CAAS_CORE_FW;                                           
grant ALTER ANY PROCEDURE to CAAS_CORE_FW;                                         
grant ALTER ANY ROLE to CAAS_CORE_FW;                                              
grant ALTER ANY SEQUENCE to CAAS_CORE_FW;                                          
grant ALTER ANY SQL PROFILE to CAAS_CORE_FW;                                       
grant ALTER ANY TABLE to CAAS_CORE_FW;                                             
grant ALTER ANY TRIGGER to CAAS_CORE_FW;                                           
grant ALTER ANY TYPE to CAAS_CORE_FW;                                              
grant ALTER DATABASE LINK to CAAS_CORE_FW;                                         
grant ALTER DATABASE to CAAS_CORE_FW;                                              
grant ALTER PROFILE to CAAS_CORE_FW;                                               
grant ALTER PUBLIC DATABASE LINK to CAAS_CORE_FW;                                  
grant ALTER RESOURCE COST to CAAS_CORE_FW;                                         
grant ALTER ROLLBACK SEGMENT to CAAS_CORE_FW;                                      
grant ALTER SESSION to CAAS_CORE_FW;                                               
grant ALTER SYSTEM to CAAS_CORE_FW;                                                
grant ALTER TABLESPACE to CAAS_CORE_FW;                                            
grant ALTER USER to CAAS_CORE_FW;                                                  
grant ANALYZE ANY DICTIONARY to CAAS_CORE_FW;                                      
grant ANALYZE ANY to CAAS_CORE_FW;                                                 
grant AUDIT ANY to CAAS_CORE_FW;                                                   
grant AUDIT SYSTEM to CAAS_CORE_FW;                                                
grant BACKUP ANY TABLE to CAAS_CORE_FW;                                            
grant BECOME USER to CAAS_CORE_FW;                                                 
grant CHANGE NOTIFICATION to CAAS_CORE_FW;                                         
grant COMMENT ANY MINING MODEL to CAAS_CORE_FW;                                    
grant COMMENT ANY TABLE to CAAS_CORE_FW;                                           
grant CREATE ANY ASSEMBLY to CAAS_CORE_FW;                                         
grant CREATE ANY CLUSTER to CAAS_CORE_FW;                                          
grant CREATE ANY CONTEXT to CAAS_CORE_FW;                                          
grant CREATE ANY CUBE BUILD PROCESS to CAAS_CORE_FW;                               
grant CREATE ANY CUBE DIMENSION to CAAS_CORE_FW;                                   
grant CREATE ANY CUBE to CAAS_CORE_FW;                                             
grant CREATE ANY DIMENSION to CAAS_CORE_FW;                                        
grant CREATE ANY DIRECTORY to CAAS_CORE_FW;                                        
grant CREATE ANY EDITION to CAAS_CORE_FW;                                          
grant CREATE ANY INDEX to CAAS_CORE_FW;                                            
grant CREATE ANY INDEXTYPE to CAAS_CORE_FW;                                        
grant CREATE ANY JOB to CAAS_CORE_FW;                                              
grant CREATE ANY LIBRARY to CAAS_CORE_FW;                                          
grant CREATE ANY MATERIALIZED VIEW to CAAS_CORE_FW;                                
grant CREATE ANY MEASURE FOLDER to CAAS_CORE_FW;                                   
grant CREATE ANY MINING MODEL to CAAS_CORE_FW;                                     
grant CREATE ANY OPERATOR to CAAS_CORE_FW;                                         
grant CREATE ANY OUTLINE to CAAS_CORE_FW;                                          
grant CREATE ANY PROCEDURE to CAAS_CORE_FW;                                        
grant CREATE ANY SEQUENCE to CAAS_CORE_FW;                                         
grant CREATE ANY SQL PROFILE to CAAS_CORE_FW;                                      
grant CREATE ANY SYNONYM to CAAS_CORE_FW;                                          
grant CREATE ANY TABLE to CAAS_CORE_FW;                                            
grant CREATE ANY TRIGGER to CAAS_CORE_FW;                                          
grant CREATE ANY TYPE to CAAS_CORE_FW;                                             
grant CREATE ANY VIEW to CAAS_CORE_FW;                                             
grant CREATE ASSEMBLY to CAAS_CORE_FW;                                             
grant CREATE CLUSTER to CAAS_CORE_FW;                                              
grant CREATE CUBE BUILD PROCESS to CAAS_CORE_FW;                                   
grant CREATE CUBE DIMENSION to CAAS_CORE_FW;                                       
grant CREATE CUBE to CAAS_CORE_FW;                                                 
grant CREATE DATABASE LINK to CAAS_CORE_FW;                                        
grant CREATE DIMENSION to CAAS_CORE_FW;                                            
grant CREATE EXTERNAL JOB to CAAS_CORE_FW;                                         
grant CREATE INDEXTYPE to CAAS_CORE_FW;                                            
grant CREATE JOB to CAAS_CORE_FW;                                                  
grant CREATE LIBRARY to CAAS_CORE_FW;                                              
grant CREATE MATERIALIZED VIEW to CAAS_CORE_FW;                                    
grant CREATE MEASURE FOLDER to CAAS_CORE_FW;                                       
grant CREATE MINING MODEL to CAAS_CORE_FW;                                         
grant CREATE OPERATOR to CAAS_CORE_FW;                                             
grant CREATE PROCEDURE to CAAS_CORE_FW;                                            
grant CREATE PROFILE to CAAS_CORE_FW;                                              
grant CREATE PUBLIC DATABASE LINK to CAAS_CORE_FW;                                 
grant CREATE PUBLIC SYNONYM to CAAS_CORE_FW;                                       
grant CREATE ROLE to CAAS_CORE_FW;                                                 
grant CREATE ROLLBACK SEGMENT to CAAS_CORE_FW;                                     
grant CREATE SEQUENCE to CAAS_CORE_FW;                                             
grant CREATE SESSION to CAAS_CORE_FW;                                              
grant CREATE SYNONYM to CAAS_CORE_FW;                                              
grant CREATE TABLE to CAAS_CORE_FW;                                                
grant CREATE TABLESPACE to CAAS_CORE_FW;                                           
grant CREATE TRIGGER to CAAS_CORE_FW;                                              
grant CREATE TYPE to CAAS_CORE_FW;                                                 
grant CREATE USER to CAAS_CORE_FW;                                                 
grant CREATE VIEW to CAAS_CORE_FW;                                                 
grant DEBUG ANY PROCEDURE to CAAS_CORE_FW;                                         
grant DEBUG CONNECT SESSION to CAAS_CORE_FW;                                       
grant DELETE ANY CUBE DIMENSION to CAAS_CORE_FW;                                   
grant DELETE ANY MEASURE FOLDER to CAAS_CORE_FW;                                   
grant DELETE ANY TABLE to CAAS_CORE_FW;                                            
grant DROP ANY ASSEMBLY to CAAS_CORE_FW;                                           
grant DROP ANY CLUSTER to CAAS_CORE_FW;                                            
grant DROP ANY CONTEXT to CAAS_CORE_FW;                                            
grant DROP ANY CUBE BUILD PROCESS to CAAS_CORE_FW;                                 
grant DROP ANY CUBE DIMENSION to CAAS_CORE_FW;                                     
grant DROP ANY CUBE to CAAS_CORE_FW;                                               
grant DROP ANY DIMENSION to CAAS_CORE_FW;                                          
grant DROP ANY DIRECTORY to CAAS_CORE_FW;                                          
grant DROP ANY EDITION to CAAS_CORE_FW;                                            
grant DROP ANY INDEX to CAAS_CORE_FW;                                              
grant DROP ANY INDEXTYPE to CAAS_CORE_FW;                                          
grant DROP ANY LIBRARY to CAAS_CORE_FW;                                            
grant DROP ANY MATERIALIZED VIEW to CAAS_CORE_FW;                                  
grant DROP ANY MEASURE FOLDER to CAAS_CORE_FW;                                     
grant DROP ANY MINING MODEL to CAAS_CORE_FW;                                       
grant DROP ANY OPERATOR to CAAS_CORE_FW;                                           
grant DROP ANY OUTLINE to CAAS_CORE_FW;                                            
grant DROP ANY PROCEDURE to CAAS_CORE_FW;                                          
grant DROP ANY ROLE to CAAS_CORE_FW;                                               
grant DROP ANY SEQUENCE to CAAS_CORE_FW;                                           
grant DROP ANY SQL PROFILE to CAAS_CORE_FW;                                        
grant DROP ANY SYNONYM to CAAS_CORE_FW;                                            
grant DROP ANY TABLE to CAAS_CORE_FW;                                              
grant DROP ANY TRIGGER to CAAS_CORE_FW;                                            
grant DROP ANY TYPE to CAAS_CORE_FW;                                               
grant DROP ANY VIEW to CAAS_CORE_FW;                                               
grant DROP PROFILE to CAAS_CORE_FW;                                                
grant DROP PUBLIC DATABASE LINK to CAAS_CORE_FW;                                   
grant DROP PUBLIC SYNONYM to CAAS_CORE_FW;                                         
grant DROP ROLLBACK SEGMENT to CAAS_CORE_FW;                                       
grant DROP TABLESPACE to CAAS_CORE_FW;                                             
grant DROP USER to CAAS_CORE_FW;                                                   
grant EXECUTE ANY ASSEMBLY to CAAS_CORE_FW;                                        
grant EXECUTE ANY CLASS to CAAS_CORE_FW;                                           
grant EXECUTE ANY INDEXTYPE to CAAS_CORE_FW;                                       
grant EXECUTE ANY LIBRARY to CAAS_CORE_FW;                                         
grant EXECUTE ANY OPERATOR to CAAS_CORE_FW;                                        
grant EXECUTE ANY PROCEDURE to CAAS_CORE_FW;                                       
grant EXECUTE ANY PROGRAM to CAAS_CORE_FW;                                         
grant EXECUTE ANY TYPE to CAAS_CORE_FW;                                            
grant EXECUTE ASSEMBLY to CAAS_CORE_FW;                                            
grant EXEMPT ACCESS POLICY to CAAS_CORE_FW;                                        
grant EXEMPT IDENTITY POLICY to CAAS_CORE_FW;                                      
grant EXPORT FULL DATABASE to CAAS_CORE_FW;                                        
grant FLASHBACK ANY TABLE to CAAS_CORE_FW;                                         
grant FLASHBACK ARCHIVE ADMINISTER to CAAS_CORE_FW;                                
grant FORCE ANY TRANSACTION to CAAS_CORE_FW;                                       
grant FORCE TRANSACTION to CAAS_CORE_FW;                                           
grant GLOBAL QUERY REWRITE to CAAS_CORE_FW;                                        
grant GRANT ANY OBJECT PRIVILEGE to CAAS_CORE_FW;                                  
grant GRANT ANY PRIVILEGE to CAAS_CORE_FW;                                         
grant GRANT ANY ROLE to CAAS_CORE_FW;                                              
grant IMPORT FULL DATABASE to CAAS_CORE_FW;                                        
grant INSERT ANY CUBE DIMENSION to CAAS_CORE_FW;                                   
grant INSERT ANY MEASURE FOLDER to CAAS_CORE_FW;                                   
grant INSERT ANY TABLE to CAAS_CORE_FW;                                            
grant LOCK ANY TABLE to CAAS_CORE_FW;                                              
grant MANAGE SCHEDULER to CAAS_CORE_FW;                                            
grant MANAGE TABLESPACE to CAAS_CORE_FW;                                           
grant MERGE ANY VIEW to CAAS_CORE_FW;                                              
grant ON COMMIT REFRESH to CAAS_CORE_FW;                                           
grant QUERY REWRITE to CAAS_CORE_FW;                                               
grant RESTRICTED SESSION to CAAS_CORE_FW;                                          
grant RESUMABLE to CAAS_CORE_FW;                                                   
grant SELECT ANY CUBE DIMENSION to CAAS_CORE_FW;                                   
grant SELECT ANY CUBE to CAAS_CORE_FW;                                             
grant SELECT ANY DICTIONARY to CAAS_CORE_FW;                                       
grant SELECT ANY MINING MODEL to CAAS_CORE_FW;                                     
grant SELECT ANY SEQUENCE to CAAS_CORE_FW;                                         
grant SELECT ANY TABLE to CAAS_CORE_FW;                                            
grant SELECT ANY TRANSACTION to CAAS_CORE_FW;                                      
grant UNDER ANY TABLE to CAAS_CORE_FW;                                             
grant UNDER ANY TYPE to CAAS_CORE_FW;                                              
grant UNDER ANY VIEW to CAAS_CORE_FW;                                              
grant UPDATE ANY CUBE BUILD PROCESS to CAAS_CORE_FW;                               
grant UPDATE ANY CUBE DIMENSION to CAAS_CORE_FW;                                   
grant UPDATE ANY CUBE to CAAS_CORE_FW;                                             
grant UPDATE ANY TABLE to CAAS_CORE_FW;                                            
CREATE FLASHBACK ARCHIVE audit_campaign TABLESPACE canoe_audit QUOTA 2G RETENTION 24 MONTH;
CREATE FLASHBACK ARCHIVE audit_media_asset TABLESPACE canoe_audit QUOTA 2G RETENTION 24 MONTH;
GRANT FLASHBACK ARCHIVE ON audit_campaign TO CAAS40;
GRANT FLASHBACK ARCHIVE ON audit_media_asset TO CAAS40;
GRANT FLASHBACK ARCHIVE ON audit_campaign TO CAAS_LOCAL;
GRANT FLASHBACK ARCHIVE ON audit_media_asset TO CAAS_LOCAL;
GRANT FLASHBACK ARCHIVE ON audit_campaign TO CAAS_CORE_FW;
GRANT FLASHBACK ARCHIVE ON audit_media_asset TO CAAS_CORE_FW;
GRANT FLASHBACK ARCHIVE ON audit_campaign TO CAAS_CORE_BRD;
GRANT FLASHBACK ARCHIVE ON audit_media_asset TO CAAS_CORE_BRD;

