CREATE USER PCI_BASE IDENTIFIED BY PCI_BASE DEFAULT TABLESPACE canoe_data_compress
TEMPORARY TABLESPACE TEMP PROFILE DEFAULT ACCOUNT UNLOCK;

GRANT TABLE_OWNER TO PCI_BASE; 
GRANT RESOURCE TO PCI_BASE;
Grant create session, alter session to PCI_BASE;
 
