CREATE USER L2L_SMSI_RPTG IDENTIFIED BY L2L_SMSI_RPTG
    default tablespace CANOE_DATA
    temporary tablespace TEMP
    profile default
    account unlock
    quota unlimited on CANOE_DATA
    quota unlimited on CANOE_INDEX
    quota unlimited on CANOE_DATA_COMPRESS;

GRANT UPDATE ANY CUBE DIMENSION TO L2L_SMSI_RPTG; 
GRANT CREATE CUBE TO L2L_SMSI_RPTG; 
GRANT SELECT ANY TRANSACTION TO L2L_SMSI_RPTG;
GRANT EXECUTE ANY CLASS TO L2L_SMSI_RPTG; 
GRANT CREATE RULE SET TO L2L_SMSI_RPTG; 
GRANT SELECT ANY DICTIONARY TO L2L_SMSI_RPTG; 
GRANT ON COMMIT REFRESH TO L2L_SMSI_RPTG; 
GRANT GLOBAL QUERY REWRITE TO L2L_SMSI_RPTG;
GRANT UNDER ANY VIEW TO L2L_SMSI_RPTG;
GRANT CREATE ANY OPERATOR TO L2L_SMSI_RPTG; 
GRANT CREATE ANY TRIGGER TO L2L_SMSI_RPTG;
GRANT DROP ANY TABLE TO L2L_SMSI_RPTG;
GRANT BECOME USER TO L2L_SMSI_RPTG; 
GRANT UNLIMITED TABLESPACE TO L2L_SMSI_RPTG;
GRANT UPDATE ANY CUBE BUILD PROCESS TO L2L_SMSI_RPTG; 
GRANT CREATE MEASURE FOLDER TO L2L_SMSI_RPTG; 
GRANT EXECUTE ANY RULE SET TO L2L_SMSI_RPTG;
GRANT CREATE ANY RULE SET TO L2L_SMSI_RPTG; 
GRANT CREATE ANY DIMENSION TO L2L_SMSI_RPTG;
GRANT EXECUTE ANY INDEXTYPE TO L2L_SMSI_RPTG; 
GRANT CREATE ANY TYPE TO L2L_SMSI_RPTG; 
GRANT CREATE TRIGGER TO L2L_SMSI_RPTG;
GRANT EXECUTE ANY PROCEDURE TO L2L_SMSI_RPTG; 
GRANT CREATE ANY SEQUENCE TO L2L_SMSI_RPTG; 
GRANT INSERT ANY TABLE TO L2L_SMSI_RPTG;
GRANT CREATE SESSION TO L2L_SMSI_RPTG;
GRANT CREATE ANY CUBE DIMENSION TO L2L_SMSI_RPTG; 
GRANT ALTER ANY CUBE DIMENSION TO L2L_SMSI_RPTG;
GRANT CREATE ANY JOB TO L2L_SMSI_RPTG;
GRANT EXECUTE ANY EVALUATION CONTEXT TO L2L_SMSI_RPTG;
GRANT DEBUG ANY PROCEDURE TO L2L_SMSI_RPTG; 
GRANT DEBUG CONNECT SESSION TO L2L_SMSI_RPTG; 
GRANT CREATE ANY CONTEXT TO L2L_SMSI_RPTG;
GRANT ENQUEUE ANY QUEUE TO L2L_SMSI_RPTG; 
GRANT CREATE ANY INDEXTYPE TO L2L_SMSI_RPTG;
GRANT CREATE ANY MATERIALIZED VIEW TO L2L_SMSI_RPTG;
GRANT CREATE SYNONYM TO L2L_SMSI_RPTG;
GRANT CREATE ANY TABLE TO L2L_SMSI_RPTG;
GRANT CREATE ANY CUBE TO L2L_SMSI_RPTG; 
GRANT CREATE ANY SQL PROFILE TO L2L_SMSI_RPTG;
GRANT ANALYZE ANY DICTIONARY TO L2L_SMSI_RPTG;
GRANT EXECUTE ANY OPERATOR TO L2L_SMSI_RPTG;
GRANT EXECUTE ANY TYPE TO L2L_SMSI_RPTG;
GRANT CREATE MATERIALIZED VIEW TO L2L_SMSI_RPTG;
GRANT CREATE ANY VIEW TO L2L_SMSI_RPTG; 
GRANT SELECT ANY TABLE TO L2L_SMSI_RPTG;
GRANT CREATE TABLE TO L2L_SMSI_RPTG;
GRANT ALTER ANY CUBE TO L2L_SMSI_RPTG;
GRANT EXECUTE ANY ASSEMBLY TO L2L_SMSI_RPTG;
GRANT EXECUTE ANY PROGRAM TO L2L_SMSI_RPTG; 
GRANT CREATE RULE TO L2L_SMSI_RPTG; 
GRANT MERGE ANY VIEW TO L2L_SMSI_RPTG;
GRANT EXECUTE ANY LIBRARY TO L2L_SMSI_RPTG; 
GRANT CREATE ANY PROCEDURE TO L2L_SMSI_RPTG;
GRANT SELECT ANY SEQUENCE TO L2L_SMSI_RPTG; 
GRANT CREATE VIEW TO L2L_SMSI_RPTG; 
GRANT CREATE PUBLIC SYNONYM TO L2L_SMSI_RPTG; 
GRANT LOCK ANY TABLE TO L2L_SMSI_RPTG;
GRANT INSERT ANY MEASURE FOLDER TO L2L_SMSI_RPTG; 
GRANT CREATE ANY MEASURE FOLDER TO L2L_SMSI_RPTG; 
GRANT SELECT ANY CUBE TO L2L_SMSI_RPTG; 
GRANT INSERT ANY CUBE DIMENSION TO L2L_SMSI_RPTG; 
GRANT CREATE ANY MINING MODEL TO L2L_SMSI_RPTG; 
GRANT CREATE INDEXTYPE TO L2L_SMSI_RPTG;
GRANT DROP ANY MATERIALIZED VIEW TO L2L_SMSI_RPTG;
GRANT CREATE SEQUENCE TO L2L_SMSI_RPTG; 
GRANT COMMENT ANY TABLE TO L2L_SMSI_RPTG; 
GRANT CREATE ANY CUBE BUILD PROCESS TO L2L_SMSI_RPTG; 
GRANT CREATE CUBE BUILD PROCESS TO L2L_SMSI_RPTG; 
GRANT UPDATE ANY CUBE TO L2L_SMSI_RPTG; 
GRANT SELECT ANY CUBE DIMENSION TO L2L_SMSI_RPTG; 
GRANT SELECT ANY MINING MODEL TO L2L_SMSI_RPTG; 
GRANT CREATE ASSEMBLY TO L2L_SMSI_RPTG; 
GRANT ALTER ANY DIMENSION TO L2L_SMSI_RPTG; 
GRANT UNDER ANY TABLE TO L2L_SMSI_RPTG; 
GRANT QUERY REWRITE TO L2L_SMSI_RPTG; 
GRANT UNDER ANY TYPE TO L2L_SMSI_RPTG;
GRANT ANALYZE ANY TO L2L_SMSI_RPTG; 
GRANT CREATE ANY SYNONYM TO L2L_SMSI_RPTG;
GRANT CREATE ANY INDEX TO L2L_SMSI_RPTG;
GRANT UPDATE ANY TABLE TO L2L_SMSI_RPTG;
GRANT CREATE CUBE DIMENSION TO L2L_SMSI_RPTG; 
GRANT CREATE JOB TO L2L_SMSI_RPTG;
GRANT EXECUTE ANY RULE TO L2L_SMSI_RPTG;
GRANT CREATE ANY RULE TO L2L_SMSI_RPTG; 
GRANT CREATE TYPE TO L2L_SMSI_RPTG; 
GRANT ALTER ANY MATERIALIZED VIEW TO L2L_SMSI_RPTG; 
GRANT CREATE PROCEDURE TO L2L_SMSI_RPTG;
GRANT DELETE ANY TABLE TO L2L_SMSI_RPTG;
GRANT SCHEDULER_ADMIN TO L2L_SMSI_RPTG;


GRANT CONNECT TO L2L_SMSI_RPTG;
GRANT RESOURCE TO L2L_SMSI_RPTG; 

ALTER USER L2L_SMSI_RPTG DEFAULT ROLE CONNECT,RESOURCE;
GRANT SELECT, REFERENCES ON CAAS_LOCAL.PROGRAMMER TO L2L_SMSI_RPTG;

GRANT SELECT, REFERENCES ON DAI_REPORTING_SAFI_TWL.VOD_SESSION_INFO TO L2L_SMSI_RPTG;
GRANT SELECT, REFERENCES ON DAI_REPORTING_SAFI_TWL.VOD_SESSION_INFO_ARCHIVE TO L2L_SMSI_RPTG;
GRANT SELECT, REFERENCES ON DAI_REPORTING_SAFI_TWL.VOD_OPPORTUNITY_ARCHIVE TO L2L_SMSI_RPTG;
GRANT SELECT, REFERENCES ON DAI_REPORTING_SAFI_TWL.VOD_PLACEMENT_ARCHIVE TO L2L_SMSI_RPTG;
GRANT SELECT, REFERENCES ON DAI_REPORTING_SAFI_TWL.VOD_VISIT_RESULT_ARCHIVE TO L2L_SMSI_RPTG;
