CREATE USER PCI_RTK IDENTIFIED BY PCI_RTK DEFAULT TABLESPACE canoe_data_compress
TEMPORARY TABLESPACE TEMP PROFILE DEFAULT ACCOUNT UNLOCK;

GRANT TABLE_OWNER TO PCI_RTK; 
GRANT RESOURCE TO PCI_RTK;
Grant create session, alter session to PCI_RTK;
 
