CREATE USER SMSI_RELAY_RTK IDENTIFIED BY SMSI_RELAY_RTK DEFAULT TABLESPACE canoe_data_compress
TEMPORARY TABLESPACE TEMP PROFILE DEFAULT ACCOUNT UNLOCK;

GRANT SELECT ANY DICTIONARY TO SMSI_RELAY_RTK;
GRANT ON COMMIT REFRESH TO SMSI_RELAY_RTK;
GRANT GLOBAL QUERY REWRITE TO SMSI_RELAY_RTK;
GRANT UNLIMITED TABLESPACE TO SMSI_RELAY_RTK;
GRANT CREATE TRIGGER TO SMSI_RELAY_RTK;
GRANT CREATE SESSION TO SMSI_RELAY_RTK;
GRANT CREATE ANY JOB TO SMSI_RELAY_RTK;
GRANT CREATE ANY MATERIALIZED VIEW TO SMSI_RELAY_RTK;
GRANT CREATE SYNONYM TO SMSI_RELAY_RTK;
GRANT CREATE MATERIALIZED VIEW TO SMSI_RELAY_RTK;
GRANT CREATE TABLE TO SMSI_RELAY_RTK;
GRANT CREATE VIEW TO SMSI_RELAY_RTK;
GRANT CREATE SEQUENCE TO SMSI_RELAY_RTK;
GRANT QUERY REWRITE TO SMSI_RELAY_RTK;
GRANT CREATE JOB TO SMSI_RELAY_RTK;
GRANT CREATE TYPE TO SMSI_RELAY_RTK;
GRANT CREATE PROCEDURE TO SMSI_RELAY_RTK;
GRANT SCHEDULER_ADMIN TO SMSI_RELAY_RTK;

GRANT RESOURCE TO SMSI_RELAY_RTK;
Grant create session, alter session to SMSI_RELAY_RTK;


GRANT SELECT, REFERENCES ON CAAS_CORE_RTK.PROGRAMMER TO SMSI_RELAY_RTK;
GRANT SELECT, REFERENCES ON CAAS_CORE_RTK.PROVIDER_NETWORK TO SMSI_RELAY_RTK;
GRANT SELECT, REFERENCES ON CAAS_CORE_RTK.NETWORK TO SMSI_RELAY_RTK;

