create user SMSI_PUB_COX identified by SMSI_PUB_COX                                     
default tablespace canoe_data                                                   
quota unlimited on canoe_data                                                   
quota unlimited on canoe_index                                                  
quota unlimited on canoe_data_compress                                          
/                                                                               
                                                                                
grant ADMINISTER ANY SQL TUNING SET to SMSI_PUB_COX;                                
grant ADMINISTER DATABASE TRIGGER to SMSI_PUB_COX;                                  
grant ADMINISTER RESOURCE MANAGER to SMSI_PUB_COX;                                  
grant ADMINISTER SQL MANAGEMENT OBJECT to SMSI_PUB_COX;                             
grant ADMINISTER SQL TUNING SET to SMSI_PUB_COX;                                    
grant ADVISOR to SMSI_PUB_COX;                                                      
grant ALTER ANY ASSEMBLY to SMSI_PUB_COX;                                           
grant ALTER ANY CLUSTER to SMSI_PUB_COX;                                            
grant ALTER ANY CUBE DIMENSION to SMSI_PUB_COX;                                     
grant ALTER ANY CUBE to SMSI_PUB_COX;                                               
grant ALTER ANY DIMENSION to SMSI_PUB_COX;                                          
grant ALTER ANY EDITION to SMSI_PUB_COX;                                            
grant ALTER ANY EVALUATION CONTEXT to SMSI_PUB_COX;                                 
grant ALTER ANY INDEX to SMSI_PUB_COX;                                              
grant ALTER ANY INDEXTYPE to SMSI_PUB_COX;                                          
grant ALTER ANY LIBRARY to SMSI_PUB_COX;                                            
grant ALTER ANY MATERIALIZED VIEW to SMSI_PUB_COX;                                  
grant ALTER ANY MINING MODEL to SMSI_PUB_COX;                                       
grant ALTER ANY OPERATOR to SMSI_PUB_COX;                                           
grant ALTER ANY OUTLINE to SMSI_PUB_COX;                                            
grant ALTER ANY PROCEDURE to SMSI_PUB_COX;                                          
grant ALTER ANY ROLE to SMSI_PUB_COX;                                               
grant ALTER ANY RULE SET to SMSI_PUB_COX;                                           
grant ALTER ANY RULE to SMSI_PUB_COX;                                               
grant ALTER ANY SEQUENCE to SMSI_PUB_COX;                                           
grant ALTER ANY SQL PROFILE to SMSI_PUB_COX;                                        
grant ALTER ANY TABLE to SMSI_PUB_COX;                                              
grant ALTER ANY TRIGGER to SMSI_PUB_COX;                                            
grant ALTER ANY TYPE to SMSI_PUB_COX;                                               
grant ALTER DATABASE LINK to SMSI_PUB_COX;                                          
grant ALTER DATABASE to SMSI_PUB_COX;                                               
grant ALTER PROFILE to SMSI_PUB_COX;                                                
grant ALTER PUBLIC DATABASE LINK to SMSI_PUB_COX;                                   
grant ALTER RESOURCE COST to SMSI_PUB_COX;                                          
grant ALTER ROLLBACK SEGMENT to SMSI_PUB_COX;                                       
grant ALTER SESSION to SMSI_PUB_COX;                                                
grant ALTER SYSTEM to SMSI_PUB_COX;                                                 
grant ALTER TABLESPACE to SMSI_PUB_COX;                                             
grant ALTER USER to SMSI_PUB_COX;                                                   
grant ANALYZE ANY DICTIONARY to SMSI_PUB_COX;                                       
grant ANALYZE ANY to SMSI_PUB_COX;                                                  
grant AUDIT ANY to SMSI_PUB_COX;                                                    
grant AUDIT SYSTEM to SMSI_PUB_COX;                                                 
grant BACKUP ANY TABLE to SMSI_PUB_COX;                                             
grant BECOME USER to SMSI_PUB_COX;                                                  
grant CHANGE NOTIFICATION to SMSI_PUB_COX;                                          
grant COMMENT ANY MINING MODEL to SMSI_PUB_COX;                                     
grant COMMENT ANY TABLE to SMSI_PUB_COX;                                            
grant CREATE ANY ASSEMBLY to SMSI_PUB_COX;                                          
grant CREATE ANY CLUSTER to SMSI_PUB_COX;                                           
grant CREATE ANY CONTEXT to SMSI_PUB_COX;                                           
grant CREATE ANY CUBE BUILD PROCESS to SMSI_PUB_COX;                                
grant CREATE ANY CUBE DIMENSION to SMSI_PUB_COX;                                    
grant CREATE ANY CUBE to SMSI_PUB_COX;                                              
grant CREATE ANY DIMENSION to SMSI_PUB_COX;                                         
grant CREATE ANY DIRECTORY to SMSI_PUB_COX;                                         
grant CREATE ANY EDITION to SMSI_PUB_COX;                                           
grant CREATE ANY EVALUATION CONTEXT to SMSI_PUB_COX;                                
grant CREATE ANY INDEX to SMSI_PUB_COX;                                             
grant CREATE ANY INDEXTYPE to SMSI_PUB_COX;                                         
grant CREATE ANY JOB to SMSI_PUB_COX;                                               
grant CREATE ANY LIBRARY to SMSI_PUB_COX;                                           
grant CREATE ANY MATERIALIZED VIEW to SMSI_PUB_COX;                                 
grant CREATE ANY MEASURE FOLDER to SMSI_PUB_COX;                                    
grant CREATE ANY MINING MODEL to SMSI_PUB_COX;                                      
grant CREATE ANY OPERATOR to SMSI_PUB_COX;                                          
grant CREATE ANY OUTLINE to SMSI_PUB_COX;                                           
grant CREATE ANY PROCEDURE to SMSI_PUB_COX;                                         
grant CREATE ANY RULE SET to SMSI_PUB_COX;                                          
grant CREATE ANY RULE to SMSI_PUB_COX;                                              
grant CREATE ANY SEQUENCE to SMSI_PUB_COX;                                          
grant CREATE ANY SQL PROFILE to SMSI_PUB_COX;                                       
grant CREATE ANY SYNONYM to SMSI_PUB_COX;                                           
grant CREATE ANY TABLE to SMSI_PUB_COX;                                             
grant CREATE ANY TRIGGER to SMSI_PUB_COX;                                           
grant CREATE ANY TYPE to SMSI_PUB_COX;                                              
grant CREATE ANY VIEW to SMSI_PUB_COX;                                              
grant CREATE ASSEMBLY to SMSI_PUB_COX;                                              
grant CREATE CLUSTER to SMSI_PUB_COX;                                               
grant CREATE CUBE BUILD PROCESS to SMSI_PUB_COX;                                    
grant CREATE CUBE DIMENSION to SMSI_PUB_COX;                                        
grant CREATE CUBE to SMSI_PUB_COX;                                                  
grant CREATE DATABASE LINK to SMSI_PUB_COX;                                         
grant CREATE DIMENSION to SMSI_PUB_COX;                                             
grant CREATE EVALUATION CONTEXT to SMSI_PUB_COX;                                    
grant CREATE EXTERNAL JOB to SMSI_PUB_COX;                                          
grant CREATE INDEXTYPE to SMSI_PUB_COX;                                             
grant CREATE JOB to SMSI_PUB_COX;                                                   
grant CREATE LIBRARY to SMSI_PUB_COX;                                               
grant CREATE MATERIALIZED VIEW to SMSI_PUB_COX;                                     
grant CREATE MEASURE FOLDER to SMSI_PUB_COX;                                        
grant CREATE MINING MODEL to SMSI_PUB_COX;                                          
grant CREATE OPERATOR to SMSI_PUB_COX;                                              
grant CREATE PROCEDURE to SMSI_PUB_COX;                                             
grant CREATE PROFILE to SMSI_PUB_COX;                                               
grant CREATE PUBLIC DATABASE LINK to SMSI_PUB_COX;                                  
grant CREATE PUBLIC SYNONYM to SMSI_PUB_COX;                                        
grant CREATE ROLE to SMSI_PUB_COX;                                                  
grant CREATE ROLLBACK SEGMENT to SMSI_PUB_COX;                                      
grant CREATE RULE SET to SMSI_PUB_COX;                                              
grant CREATE RULE to SMSI_PUB_COX;                                                  
grant CREATE SEQUENCE to SMSI_PUB_COX;                                              
grant CREATE SESSION to SMSI_PUB_COX;                                               
grant CREATE SYNONYM to SMSI_PUB_COX;                                               
grant CREATE TABLE to SMSI_PUB_COX;                                                 
grant CREATE TABLESPACE to SMSI_PUB_COX;                                            
grant CREATE TRIGGER to SMSI_PUB_COX;                                               
grant CREATE TYPE to SMSI_PUB_COX;                                                  
grant CREATE USER to SMSI_PUB_COX;                                                  
grant CREATE VIEW to SMSI_PUB_COX;                                                  
grant DEBUG ANY PROCEDURE to SMSI_PUB_COX;                                          
grant DEBUG CONNECT SESSION to SMSI_PUB_COX;                                        
grant DELETE ANY CUBE DIMENSION to SMSI_PUB_COX;                                    
grant DELETE ANY MEASURE FOLDER to SMSI_PUB_COX;                                    
grant DELETE ANY TABLE to SMSI_PUB_COX;                                             
grant DEQUEUE ANY QUEUE to SMSI_PUB_COX;                                            
grant DROP ANY ASSEMBLY to SMSI_PUB_COX;                                            
grant DROP ANY CLUSTER to SMSI_PUB_COX;                                             
grant DROP ANY CONTEXT to SMSI_PUB_COX;                                             
grant DROP ANY CUBE BUILD PROCESS to SMSI_PUB_COX;                                  
grant DROP ANY CUBE DIMENSION to SMSI_PUB_COX;                                      
grant DROP ANY CUBE to SMSI_PUB_COX;                                                
grant DROP ANY DIMENSION to SMSI_PUB_COX;                                           
grant DROP ANY DIRECTORY to SMSI_PUB_COX;                                           
grant DROP ANY EDITION to SMSI_PUB_COX;                                             
grant DROP ANY EVALUATION CONTEXT to SMSI_PUB_COX;                                  
grant DROP ANY INDEX to SMSI_PUB_COX;                                               
grant DROP ANY INDEXTYPE to SMSI_PUB_COX;                                           
grant DROP ANY LIBRARY to SMSI_PUB_COX;                                             
grant DROP ANY MATERIALIZED VIEW to SMSI_PUB_COX;                                   
grant DROP ANY MEASURE FOLDER to SMSI_PUB_COX;                                      
grant DROP ANY MINING MODEL to SMSI_PUB_COX;                                        
grant DROP ANY OPERATOR to SMSI_PUB_COX;                                            
grant DROP ANY OUTLINE to SMSI_PUB_COX;                                             
grant DROP ANY PROCEDURE to SMSI_PUB_COX;                                           
grant DROP ANY ROLE to SMSI_PUB_COX;                                                
grant DROP ANY RULE SET to SMSI_PUB_COX;                                            
grant DROP ANY RULE to SMSI_PUB_COX;                                                
grant DROP ANY SEQUENCE to SMSI_PUB_COX;                                            
grant DROP ANY SQL PROFILE to SMSI_PUB_COX;                                         
grant DROP ANY SYNONYM to SMSI_PUB_COX;                                             
grant DROP ANY TABLE to SMSI_PUB_COX;                                               
grant DROP ANY TRIGGER to SMSI_PUB_COX;                                             
grant DROP ANY TYPE to SMSI_PUB_COX;                                                
grant DROP ANY VIEW to SMSI_PUB_COX;                                                
grant DROP PROFILE to SMSI_PUB_COX;                                                 
grant DROP PUBLIC DATABASE LINK to SMSI_PUB_COX;                                    
grant DROP PUBLIC SYNONYM to SMSI_PUB_COX;                                          
grant DROP ROLLBACK SEGMENT to SMSI_PUB_COX;                                        
grant DROP TABLESPACE to SMSI_PUB_COX;                                              
grant DROP USER to SMSI_PUB_COX;                                                    
grant ENQUEUE ANY QUEUE to SMSI_PUB_COX;                                            
grant EXECUTE ANY ASSEMBLY to SMSI_PUB_COX;                                         
grant EXECUTE ANY CLASS to SMSI_PUB_COX;                                            
grant EXECUTE ANY EVALUATION CONTEXT to SMSI_PUB_COX;                               
grant EXECUTE ANY INDEXTYPE to SMSI_PUB_COX;                                        
grant EXECUTE ANY LIBRARY to SMSI_PUB_COX;                                          
grant EXECUTE ANY OPERATOR to SMSI_PUB_COX;                                         
grant EXECUTE ANY PROCEDURE to SMSI_PUB_COX;                                        
grant EXECUTE ANY PROGRAM to SMSI_PUB_COX;                                          
grant EXECUTE ANY RULE SET to SMSI_PUB_COX;                                         
grant EXECUTE ANY RULE to SMSI_PUB_COX;                                             
grant EXECUTE ANY TYPE to SMSI_PUB_COX;                                             
grant EXECUTE ASSEMBLY to SMSI_PUB_COX;                                             
grant EXEMPT ACCESS POLICY to SMSI_PUB_COX;                                         
grant EXEMPT IDENTITY POLICY to SMSI_PUB_COX;                                       
grant EXPORT FULL DATABASE to SMSI_PUB_COX;                                         
grant FLASHBACK ANY TABLE to SMSI_PUB_COX;                                          
grant FLASHBACK ARCHIVE ADMINISTER to SMSI_PUB_COX;                                 
grant FORCE ANY TRANSACTION to SMSI_PUB_COX;                                        
grant FORCE TRANSACTION to SMSI_PUB_COX;                                            
grant GLOBAL QUERY REWRITE to SMSI_PUB_COX;                                         
grant GRANT ANY OBJECT PRIVILEGE to SMSI_PUB_COX;                                   
grant GRANT ANY PRIVILEGE to SMSI_PUB_COX;                                          
grant GRANT ANY ROLE to SMSI_PUB_COX;                                               
grant IMPORT FULL DATABASE to SMSI_PUB_COX;                                         
grant INSERT ANY CUBE DIMENSION to SMSI_PUB_COX;                                    
grant INSERT ANY MEASURE FOLDER to SMSI_PUB_COX;                                    
grant INSERT ANY TABLE to SMSI_PUB_COX;                                             
grant LOCK ANY TABLE to SMSI_PUB_COX;                                               
grant MANAGE ANY FILE GROUP to SMSI_PUB_COX;                                        
grant MANAGE ANY QUEUE to SMSI_PUB_COX;                                             
grant MANAGE FILE GROUP to SMSI_PUB_COX;                                            
grant MANAGE SCHEDULER to SMSI_PUB_COX;                                             
grant MANAGE TABLESPACE to SMSI_PUB_COX;                                            
grant MERGE ANY VIEW to SMSI_PUB_COX;                                               
grant ON COMMIT REFRESH to SMSI_PUB_COX;                                            
grant QUERY REWRITE to SMSI_PUB_COX;                                                
grant READ ANY FILE GROUP to SMSI_PUB_COX;                                          
grant RESTRICTED SESSION to SMSI_PUB_COX;                                           
grant RESUMABLE to SMSI_PUB_COX;                                                    
grant SELECT ANY CUBE DIMENSION to SMSI_PUB_COX;                                    
grant SELECT ANY CUBE to SMSI_PUB_COX;                                              
grant SELECT ANY DICTIONARY to SMSI_PUB_COX;                                        
grant SELECT ANY MINING MODEL to SMSI_PUB_COX;                                      
grant SELECT ANY SEQUENCE to SMSI_PUB_COX;                                          
grant SELECT ANY TABLE to SMSI_PUB_COX;                                             
grant SELECT ANY TRANSACTION to SMSI_PUB_COX;                                       
grant UNDER ANY TABLE to SMSI_PUB_COX;                                              
grant UNDER ANY TYPE to SMSI_PUB_COX;                                               
grant UNDER ANY VIEW to SMSI_PUB_COX;                                               
grant UNLIMITED TABLESPACE to SMSI_PUB_COX;                                         
grant UPDATE ANY CUBE BUILD PROCESS to SMSI_PUB_COX;                                
grant UPDATE ANY CUBE DIMENSION to SMSI_PUB_COX;                                    
grant UPDATE ANY CUBE to SMSI_PUB_COX;                                              
grant UPDATE ANY TABLE to SMSI_PUB_COX;                                             
grant CONNECT to SMSI_PUB_COX;                                                      
grant RESOURCE to SMSI_PUB_COX;                                                     
