CREATE USER TMPDAIDCE IDENTIFIED BY TMPDAIDCE;
ALTER USER TMPDAIDCE QUOTA UNLIMITED ON CANOE_DATA;
ALTER USER TMPDAIDCE QUOTA UNLIMITED ON CANOE_DATA_COMPRESS;
ALTER USER TMPDAIDCE QUOTA UNLIMITED ON CANOE_DATA_COMPRESS2;
ALTER USER TMPDAIDCE QUOTA UNLIMITED ON CANOE_INDEX;
GRANT TABLE_OWNER TO TMPDAIDCE;
GRANT CONNECT, RESOURCE, CREATE ANY SYNONYM, CREATE VIEW, CREATE TRIGGER, CREATE ANY TRIGGER, CREATE MATERIALIZED VIEW, CREATE ANY MATERIALIZED VIEW, UNLIMITED TABLESPACE TO TMPDAIDCE;
